#b1、在配置文件中指定 spring.profiles.active=dev
# 2、命令行：
#  java -jar spring-boot-02-config-0.0.1-SNAPSHOT.jar --spring.profiles.active=dev；
#  可以直接在测试的时候，配置传入命令行参数
# 3、虚拟机参数(VM options)；
#  -Dspring.profiles.active=dev
# 4、项目参数(Project Arguments)
#  --spring.profiles.active=dev


#server:
#  port: 8081
#
#spring:
#  profiles:
#    active: prod
#---
#server:
#  port: 8091
#
#spring:
#  profiles: dev
#---
#
#server:
#  port: 8092
#  
#spring:
#  profiles: prod
    
#person:
#  name: JLC
#  age: 20
#  birthday: 2019/10/11
#  tools: [idea, eclipse, tomcat]
#  friends: {f1: ghx, f2: gcy, f3: lx, f4: mj}
#  dog: 
#    name: 小黑
#    age: 2